version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    image: snap-hutao-passport-web
    container_name: Snap-Hutao-Passport-Web
    ports:
      - "3971:80"
    restart: unless-stopped
    depends_on:
      - tunnel

  tunnel:
    container_name: Snap-Hutao-Passport-Web-Tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=token